CREATE TABLE IF NOT EXISTS WORDS(
	WOR_ID NUMERIC(10) NOT NULL,
	WOR_WORD VARCHAR(20),
	WOR_LANG_CODE VARCHAR(2),
	WOR_DIFFICULTY NUMERIC(1),
	PRIMARY KEY (WOR_ID)
);

COMMENT ON COLUMN WORDS.WOR_ID IS 'Unique identifier';
COMMENT ON COLUMN WORDS.WOR_WORD IS 'Word (noun)';
COMMENT ON COLUMN WORDS.WOR_LANG_CODE IS 'Two-digit language code';
COMMENT ON COLUMN WORDS.WOR_DIFFICULTY IS 'Difficulty (1 - easy, 2 - normal, 3 - hard)';

CREATE SEQUENCE IF NOT EXISTS SEQ_WOR_ID INCREMENT BY 1 START WITH 1 NO CYCLE OWNED BY WORDS.WOR_ID;