CREATE TABLE PLAYERS(
	ID NUMERIC(10) NOT NULL,
	NAME VARCHAR(30) NOT NULL,
	TEAM_ID NUMERIC(10) NOT NULL,
	ROLE VARCHAR(1) NOT NULL,
	PRIMARY KEY (ID),
	CONSTRAINT FK_TEAM_ID FOREIGN KEY (TEAM_ID) REFERENCES TEAMS (ID)
);

CREATE SEQUENCE IF NOT EXISTS SEQ_PLAYERS_ID INCREMENT BY 1 START WITH 1 CYCLE OWNED BY PLAYERS.ID;

CREATE UNIQUE INDEX IDX_NAME_TEAM_ID ON PLAYERS (NAME, TEAM_ID);

COMMENT ON COLUMN PLAYERS.ID IS 'Unique identifier';
COMMENT ON COLUMN PLAYERS.NAME IS 'Player name';
COMMENT ON COLUMN PLAYERS.TEAM_ID IS 'Identifier of a team player is a part of';
COMMENT ON COLUMN PLAYERS.ROLE IS 'Players role (S - spymaster, P - regular player)';