ALTER TABLE PLAYERS ADD COLUMN LOBBY_ID NUMERIC(10);
COMMENT ON COLUMN PLAYERS.LOBBY_ID IS 'Identifier of a lobby the player is a part of';
ALTER TABLE PLAYERS ADD CONSTRAINT FK_LOBBY_ID FOREIGN KEY (LOBBY_ID) REFERENCES LOBBIES(ID);