CREATE TABLE LOBBIES(
	ID NUMERIC(10) NOT NULL,
	JOIN_CODE VARCHAR(6) NOT NULL,
	LANGUAGE VARCHAR(2),
	WORDS JSONB,
	PRIMARY KEY (ID)
);

COMMENT ON COLUMN LOBBIES.ID IS 'Unique identifier';
COMMENT ON COLUMN LOBBIES.JOIN_CODE IS 'Code to join a lobby';
COMMENT ON COLUMN LOBBIES.LANGUAGE IS 'Two-digit language code';
COMMENT ON COLUMN LOBBIES.WORDS IS 'Current words in play';

CREATE SEQUENCE IF NOT EXISTS SEQ_LOBBIES_ID INCREMENT BY 1 START WITH 1 CYCLE OWNED BY LOBBIES.ID;

CREATE UNIQUE INDEX IDX_LOBBIES_JOIN_CODE ON LOBBIES (JOIN_CODE);